### ISSUE TITLE
Add transition when lazily loaded image unveils

### ISSUE THREAD

**Issue by johannschopplich** [johannschopplich/kirby-blurry-placeholder#2]

**Comment by johannschopplich** [comment]
Closing, because it needs to be handled entirely in the frontend and is beyond the scope of the core of this plugin.

**Comment by DodoVoelkel** [comment]
> Closing, because it needs to be handled entirely in the frontend and is beyond the scope of the core of this plugin.

So how whould you tackle that problem? As i believe there is no possibility for that if its handled with src and srcset, or am I wrong?

**Comment by johannschopplich** [comment]
It's pretty straight-forward. You just have to add another layer (including image) on top of the blurry image. The latter one stays in place, while the lazily loaded image gets the revealing effect. We use JavaScript to detect once the image has been loaded.

Example setup:

```html
<figure class="blurry-image">
  <img data-lazyload data-src="<?= $image->url() ?>" class="image-to-reveal">
  <!-- The blurry image will stay in place -->
  <img src="<?= $image->placeholderUri() ?>">
</figure>
```

```css
.blurry-image {
  display: grid;
}

.blurry-image > * {
  grid-area: 1 / 1 / 1 / 1;
}

.image-to-reveal {
  opacity: 0;
  transition: opacity 250ms ease;
}

.image-to-reveal.has-loaded {
  opacity: 1;
}
```

With [Loadeer](https://github.com/johannschopplich/loadeer):

```js
const instance = new Loadeer('[data-lazyload]', {
  onLoaded: (element) => {
    element.addEventListener('load', ({ target }) => target.classList.add('has-loaded'))
  }
})
instance.observe()
```
